// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
// import { supabase } from "@/integrations/supabase/client";

// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL = "https://hppavhfhnngsafvetfvt.supabase.co"
const SUPABASE_PUBLISHABLE_KEY ="sb_publishable_eISKWV3En9AJcHWtBfvp5w_pB518s1S";

// Import the supabase client like this:


export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});